import Navbar from "@/components/Navbar";
import { useAllTips } from "@/hooks/useAllTips";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const { data: allTips, isSuccess } = useAllTips();

  if (!isSuccess) return <div>Loading...</div>;
  const tips = allTips.filter((tip) => tip.approved && !tip.rejected);
  const randomTip = tips[Math.floor(Math.random() * tips.length)];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="h-[100vh] w-[100vw] bg-[url('/images/room2.png')] bg-cover bg-center bg-no-repeat">
        <div className="flex h-full w-full flex-col-reverse items-center justify-center md:justify-normal">
          <Image
            className="
              w-[95%] sm:w-[65%] md:mb-[10%] md:w-[55%]
              lg:mb-[5%] lg:w-[50%]
              "
            src="/images/note.png"
            alt="room"
            width={1920}
            height={1080}
          ></Image>
          <div
            className="absolute mt-[20%] h-[55vw] w-[75%]
              sm:mt-[7%] sm:h-[36vw] sm:w-[50%]
              md:mb-[18%] md:h-[33vw] md:w-[45%]
              lg:mb-[12%] lg:h-[30vw] lg:w-[40%]"
          >
            <div
              className="h-full w-full break-normal px-[10vw]
              text-[4.8vw] leading-[14vw]
              sm:px-[6vw] sm:pt-[3vw] sm:text-[24px] sm:leading-[9.5vw]
              md:px-[5.5vw] md:pt-[3vw] md:text-[28px] md:leading-[8vw]
              lg:px-[5vw] lg:pt-[3vw] lg:text-[32px] lg:leading-[7.5vw] 
              "
            >
              {randomTip?.content}
            </div>
            <div className="absolute bottom-[1vw] right-[1vw] text-end text-[4.8vw] font-semibold sm:text-[24px] md:text-[28px] lg:text-[32px]">
              {randomTip?.writerName}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
